#!/usr/bin/env python3
# ─────────────────────────────────────────────────────────────
#  tests/analyze_qos.py  —  Step 4: QoS Graph Generator
#
#  Reads the CSV files generated by QoSMonitor and plots:
#    1. Latency over time
#    2. Throughput over time
#    3. Chunk size over time (adaptive bitrate)
#
#  Usage:
#    python tests/analyze_qos.py                    (latest CSV)
#    python tests/analyze_qos.py qos_client1_x.csv  (specific file)
# ─────────────────────────────────────────────────────────────

import csv
import os
import sys
import glob

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(BASE_DIR, "..")
sys.path.insert(0, ROOT_DIR)

try:
    import matplotlib.pyplot as plt
    import matplotlib.gridspec as gridspec
    MATPLOTLIB_OK = True
except ImportError:
    MATPLOTLIB_OK = False
    print("[Analyze] matplotlib not found.")
    print("[Analyze] Install with:  pip install matplotlib")


def find_latest_csv():
    """Find the most recently created QoS CSV in project root."""
    pattern = os.path.join(ROOT_DIR, "qos_client*.csv")
    files   = glob.glob(pattern)
    if not files:
        return None
    return max(files, key=os.path.getctime)


def load_csv(filepath: str):
    """Load CSV into lists of metrics."""
    seq_nums    = []
    latencies   = []
    throughputs = []
    chunk_sizes = []

    with open(filepath, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            seq_nums.append(int(row["seq_num"]))
            latencies.append(float(row["latency_ms"]))
            throughputs.append(float(row["throughput_kbps_instant"]))
            chunk_sizes.append(int(row["chunk_size_bytes"]))

    return seq_nums, latencies, throughputs, chunk_sizes


def print_stats(latencies, throughputs):
    """Print summary statistics to terminal."""
    print(f"\n{'='*50}")
    print(f"  QoS ANALYSIS SUMMARY")
    print(f"{'='*50}")
    print(f"  Total chunks    : {len(latencies)}")
    print(f"  Avg Latency     : {round(sum(latencies)/len(latencies), 2)} ms")
    print(f"  Max Latency     : {round(max(latencies), 2)} ms")
    print(f"  Min Latency     : {round(min(latencies), 2)} ms")
    print(f"  Avg Throughput  : {round(sum(throughputs)/len(throughputs), 2)} KB/s")
    print(f"  Peak Throughput : {round(max(throughputs), 2)} KB/s")
    print(f"{'='*50}\n")


def plot_qos(filepath: str):
    """Generate QoS graphs from CSV file."""
    print(f"[Analyze] Loading: {os.path.basename(filepath)}")

    seq_nums, latencies, throughputs, chunk_sizes = load_csv(filepath)
    print_stats(latencies, throughputs)

    if not MATPLOTLIB_OK:
        print("[Analyze] Cannot plot — matplotlib not installed.")
        print("[Analyze] Stats printed above instead.")
        return

    # ── Plot 3 graphs ─────────────────────────────────────────
    fig = plt.figure(figsize=(12, 9))
    fig.suptitle(f"QoS Analysis — {os.path.basename(filepath)}",
                 fontsize=13, fontweight="bold")

    gs = gridspec.GridSpec(3, 1, hspace=0.5)

    # Graph 1: Latency per chunk
    ax1 = fig.add_subplot(gs[0])
    ax1.plot(seq_nums, latencies, color="#00b4d8", linewidth=0.8, alpha=0.8)
    ax1.axhline(sum(latencies)/len(latencies), color="#ff6b6b",
                linestyle="--", linewidth=1, label="Avg")
    ax1.set_title("Latency (RTT) per Chunk", fontsize=10)
    ax1.set_xlabel("Chunk Sequence Number")
    ax1.set_ylabel("Latency (ms)")
    ax1.legend(fontsize=8)
    ax1.grid(True, alpha=0.3)

    # Graph 2: Throughput over time
    ax2 = fig.add_subplot(gs[1])
    ax2.plot(seq_nums, throughputs, color="#a8ff78", linewidth=0.8, alpha=0.8)
    ax2.axhline(sum(throughputs)/len(throughputs), color="#ff6b6b",
                linestyle="--", linewidth=1, label="Avg")
    ax2.set_title("Cumulative Throughput over Time", fontsize=10)
    ax2.set_xlabel("Chunk Sequence Number")
    ax2.set_ylabel("Throughput (KB/s)")
    ax2.legend(fontsize=8)
    ax2.grid(True, alpha=0.3)

    # Graph 3: Chunk size (adaptive bitrate)
    ax3 = fig.add_subplot(gs[2])
    ax3.plot(seq_nums, [s/1024 for s in chunk_sizes],
             color="#ffcc02", linewidth=0.8, alpha=0.8)
    ax3.set_title("Chunk Size over Time (Adaptive Bitrate)", fontsize=10)
    ax3.set_xlabel("Chunk Sequence Number")
    ax3.set_ylabel("Chunk Size (KB)")
    ax3.grid(True, alpha=0.3)

    # Save graph as PNG
    out_file = filepath.replace(".csv", "_graph.png")
    plt.savefig(out_file, dpi=150, bbox_inches="tight",
                facecolor="#0a0a0f")
    print(f"[Analyze] Graph saved → {out_file}")
    plt.show()


if __name__ == "__main__":
    if len(sys.argv) > 1:
        csv_file = sys.argv[1]
    else:
        csv_file = find_latest_csv()

    if not csv_file or not os.path.exists(csv_file):
        print("[Analyze] No QoS CSV file found.")
        print("[Analyze] Stream a song first — CSV is auto-generated after each session.")
    else:
        plot_qos(csv_file)
